
name = "medical-triage-simulator"
compatibility_date = "2025-05-07"
main = "./dist/index.html"
workers_dev = true

[site]
bucket = "./dist"

[build]
command = "npm run build"

[site.upload]
format = "service-worker"
